version: '3'

volumes:
  ayushma_local_postgres_data: {}
  ayushma_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django
    container_name: ayushma_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres
    container_name: ayushma_local_postgres
    volumes:
      - ayushma_local_postgres_data:/var/lib/postgresql/data:Z
      - ayushma_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: ayushma_local_redis

  celeryworker:
    <<: *django
    image: ayushma_local_celeryworker
    container_name: ayushma_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ayushma_local_celerybeat
    container_name: ayushma_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
